message: Greetings from the COSTBO-ACCOUNT-QUERY-SIDE microservice [using the PRODUCTION config].
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: costbo_events.fanout.exchange
        queue: account_events.queue
        terminal: costbo.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/accounts_qry

