message: Greetings from the COSTBO-BUSINESS-COMMAND-SIDE microservice [using the PRODUCTION config].
server:
  port: 9100
#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: costbo_events.fanout.exchange
        queue: business_events.queue
        databaseName: business_events
        eventsCollectionName: business_events
        snapshotCollectionName: business_snapshots
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/business_cmd

