message: Greetings from the COSTBO-CONTACT-COMMAND-SIDE microservice [using the PRODUCTION config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: accounts.events.fanout.exchange
        queue: accounts.default.queue
        databaseName: contact_events
        eventsCollectionName: contacts_events
        snapshotCollectionName: contacts_snapshots
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/contacts_cmd

