message: Greetings from the CONTACT-QUERY-SIDE microservice [using the LOCALHOST config].

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: contacts.events.fanout.exchange
        queue: event.stream
        terminal: contacts.axon.terminal
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/contacts_qry

