message: Greetings from the CONTACT-COMMAND-SIDE microservice [using the LOCALHOST config].
server:
  port: 7000
#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: costbo_events.fanout.exchange
        queue: contact_events.queue
        databaseName: contact_events
        eventsCollectionName: contacts_events
        snapshotCollectionName: contacts_snapshots
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://localhost:27017/contacts_cmd

