message: Greetings from the CONTACT-QUERY-SIDE microservice [using the LOCALHOST config].
server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: costbo_events.fanout.exchange
        queue: contact_events.queue
        terminal: costbo.axon.terminal
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/contacts_qry

