message: Greetings from the CONTACT-COMMAND-SIDE microservice [using the LOCALHOST config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: contacts.events.fanout.exchange
        queue: contacts.default.queue
        databaseName: contact_events
        eventsCollectionName: contacts_events
        snapshotCollectionName: contacts_snapshots
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://localhost:27017/contacts_cmd
logging:
    level:
        root: INFO
        org.springframework: INFO
            aop: DEBUG
            dao: DEBUG
            orm: DEBUG
            amqp: DEBUG
            data: DEBUG
            transaction: DEBUG
        org.axonframework: DEBUG
        com.costbo: DEBUG
    file: ./build/logs/command-side-server.log
