message: Greetings from the COSTBO-CONTACT-QUERY-SIDE microservice [using the PRODUCTION config].

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: contacts.events.fanout.exchange
        queue: event.stream
        terminal: contacts.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/contacts_qry
logging:
    level:
        root: WARN
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.costbo: INFO
    file: ./logs/query-side-server.log
