message: Greetings from the COSTBO-CONTACT-QUERY-SIDE microservice [using the PRODUCTION config].
server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: contacts.events.fanout.exchange
        queue: event.stream
        terminal: contacts.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/contacts_qry

